# Generated by Django 3.0.8 on 2020-08-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=256, verbose_name='Производитель')),
                ('model', models.CharField(max_length=256, verbose_name='Модель авто')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('transmission', models.SmallIntegerField(choices=[(1, 'механика'), (2, 'автомат'), (3, 'робот')], verbose_name='Коробка передач')),
                ('color', models.SmallIntegerField(choices=[(1, 'Красный'), (2, 'Белый'), (3, 'Черный'), (1, 'Фиолетовый'), (2, 'Синий'), (3, 'Зеленый')], verbose_name='Цвет')),
            ],
        ),
    ]
