# Generated by Django 3.0.8 on 2020-08-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[(1, 'Красный'), (2, 'Белый'), (3, 'Черный'), (1, 'Фиолетовый'), (2, 'Синий'), (3, 'Зеленый')], max_length=33, verbose_name='Цвет'),
        ),
    ]
