# Generated by Django 3.0.8 on 2020-08-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200827_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('механика', 1), ('автомат', 2), ('робот', 3)], verbose_name='Коробка передач'),
        ),
    ]
