# Generated by Django 3.0.8 on 2020-08-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200828_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Красный', 1), ('Белый', 2), ('Черный', 3), ('Фиолетовый', 4), ('Синий', 5), ('Зеленый', 6)], max_length=33, verbose_name='Цвет'),
        ),
    ]
