# Generated by Django 3.0.8 on 2020-08-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200828_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.SmallIntegerField(choices=[('Красный', 'Красный'), ('Белый', 'Белый'), ('Черный', 'Черный'), ('Фиолетовый', 'Фиолетовый'), ('Синий', 'Синий'), ('Зеленый', 'Зеленый')], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('механика', 'механика'), ('автомат', 'автомат'), ('робот', 'робот')], verbose_name='Коробка передач'),
        ),
    ]
